# Generated by Django 3.2.6 on 2022-01-31 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturent_apiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratting', models.FloatField(default=0)),
                ('body', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='reviews',
            field=models.ManyToManyField(blank=True, null=True, related_name='reviews', to='resturent_apiApp.Reviews'),
        ),
    ]
