# Generated by Django 3.2.6 on 2021-12-21 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturent_apiApp', '0002_alter_returent_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returent',
            name='user',
        ),
    ]
