# Generated by Django 3.2.6 on 2022-02-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturent_apiApp', '0002_auto_20220131_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='name',
            field=models.CharField(default='name', max_length=1000),
        ),
    ]
