# Generated by Django 3.2.6 on 2022-01-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturent_apiApp', '0004_item_item_structor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returent',
            name='image',
            field=models.ImageField(blank=True, default='media/dineinImages/pexels-adonyi-gábor-1414651_1cjSUoF.jpg', null=True, upload_to='media/dineinImages'),
        ),
    ]
