# Generated by Django 3.2.6 on 2022-01-19 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resturent_apiApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/profileImage')),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('business_account', models.BooleanField(default=False)),
                ('rider_account', models.BooleanField(default=False)),
                ('Followes', models.ManyToManyField(blank=True, null=True, related_name='flowwers', to=settings.AUTH_USER_MODEL)),
                ('returent', models.ManyToManyField(blank=True, null=True, related_name='returent', to='resturent_apiApp.Returent')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
